### PR TITLE
fix: PagesProgressBar shallowRouting

### LINKED ISSUE #68: `shallowRouting` doesn't work
reproduce: 

1. open the [codesandbox](https://codesandbox.io/p/devbox/musing-dhawan-xpdq2m)
2. click `nextRouter` link in the index page
3. click button `UPDATE QUERY`, still show the nprogress

The key problems is when I the `shallowRouting=true`, should not display thre nprogress when I run following code:

```typescript
router.push(
    {
        pathname: router.pathname,
        query: {
            tab: 'album',
        },
    },
    undefined,
    { shallow: true },
);
```

### PR DESCRIPTION
**Pull request by l0gicgate**
## Description

This matches the logic that is contained in `AppProgressBar` for `shallowRouting`.

Closes #68

### CODE REVIEW

**Comment by l0gicgate** [comment]
@Skyleen77 can you take a look at this when you have a minute please 🙏🏼 

Would love to have a release for this as soon as possible if you agree with the proposed changes.

**Comment by l0gicgate** [comment]
Good morning @Skyleen77, can you please take a look at this as soon as you can. It is a blocker for us at my work at the moment 🙏🏼

**Comment by l0gicgate** [comment]
@Skyleen77 can you please take a look a this? This is blocking us 😢

**Comment by Skyleen77** [comment]
Sorry for the delay. You can update your package to version 2.3.16.

**Comment by l0gicgate** [comment]
You are awesome @Skyleen77 thank you!

**Pull request merged**
