### PR TITLE
fix: fix #5 number issue for href-less anchors

### LINKED ISSUE #5: Uncaught TypeError: Failed to construct 'URL': Invalid URL at HTMLAnchorElement.handleAnchorClick
Uncaught TypeError: Failed to construct 'URL': Invalid URL at HTMLAnchorElement.handleAnchorClick (webpack-internal:///(app-client)/./node_modules/next-nprogress-bar/dist/index.js:66:29)

Screenshot from 2023-07-06 12-21-04

next-nprogress-bar works fantastic with nextjs 13 App router, but it gives an issue when I use it with Fullcalendar.
Fullcalendar render all events with `anchor` tag without `href` attribute (non-URL), on event click next-nprogress-bar return error message mentioned above.

### PR DESCRIPTION
**Pull request by NdungutseCharles103**
Just fixed the issue #5 for anchors without href attribut plus skipping anchors with target="_blank"

### CODE REVIEW

**Comment by yurii-holenko** [comment]
why there is linter changes in PR, mb next time do no mix features and linter changes?

**Comment by Skyleen77** [comment]
> why there is linter changes in PR, mb next time do no mix features and linter changes?

You are right. This is not disturbing because it is a small feature on a small package.

I simply updated the modified files with the correct linter.

Thank you for your comment.

**Comment by Skyleen77** [comment]
> Just fixed the issue #5 for anchors without href attribut plus skipping anchors with target="_blank"

Try next time to use the correct linter.

Thank you for your contribution.

**Comment by NdungutseCharles103** [comment]
> > Just fixed the issue #5 for anchors without href attribut plus skipping anchors with target="_blank"
> 
> Try next time to use the correct linter.
> 
> Thank you for your contribution.

I think it was because my editor was falsely configured ( to use eslint editor configuration not for the workspace)

**Comment by Skyleen77** [comment]
> > > Just fixed the issue #5 for anchors without href attribut plus skipping anchors with target="_blank"
> > 
> > 
> > Try next time to use the correct linter.
> > Thank you for your contribution.
> 
> I think it was because my editor was falsely configured ( to use eslint editor configuration not for the workspace)

It's okay, don't worry, thank you anyway.

**Pull request merged**
